### ISSUE TITLE
Pass options to scenario

### ISSUE THREAD

**Issue by elrickvm** [thefrontside/simulacrum#63]
We need to be able to pass options to scenarios. For example, we need to be able to test the case of when a user exists in Auth0 vs when they don't. This means being able to specify at scenario creation time how that scenario will behave.

**Comment by cowboyd** [comment]
@dagda1 current branch is at https://github.com/thefrontside/simulacrum/tree/scenario-parameters

Currently, the person scenario accepts parameters as:

```ts
await client.given(simulation, "person", {
  name: 'Bartholomew Blecht'
});
```

But per today's discussion, we should sequester each set of properties according to the simulator that will consume them:


```ts
await client.given(simulation, "person", {
  person: {
    name: 'Bartholomew Blecht'
 }
});
```

This probably won't change the way the core parameter passing is implemented, but it will mean that the `person` scenario in the `person` simulator, will need to look in params.person.name instead of just params.name.

**Comment by elrickvm** [comment]
@cowboyd @dagda1 does PR #67 close this issue?
